#!/bin/sh

for i in $TARGET;
do
case $i in
  pandoc)
    cabal install --flags="embed_data_files" pandoc pandoc-citeproc
    cp ~/.cabal/bin/pandoc* ./
    ;;
  texlive)
    tar zxf install-tl*
    ./install-tl*/install-tl -profile TexLive.profile
    sudo ~/texlive/bin/x86_64-linux/tlmgr path add
    tlmgr install $(cat TeXLive.pkgs | tr '\n' ' ')
    equivs-build debian-*
    mv texlive-local*.deb texlive-local.deb
    cd ~
    tar zcf texlive.tar.gz texlive
    cp texlive.tar.gz $TRAVIS_BUILD_DIR
    ;;
  *)
    echo "nothing to build"
    ;;
esac
done
