#!/bin/sh

for i in $TARGET;
do
case $i in
  pandoc)
    sudo apt-get install -qq haskell-platform
    cabal update
    cabal install hsb2hs
    ;;
  r-devel)
    wget http://cran.rstudio.com/src/base-prerelease/R-latest.tar.gz
    sudo apt-get -qq build-dep r-base
    ;;
  texlive)
    sudo apt-get -qq install equivs
    sed -i 's@\$HOME@'"$HOME"'@' TexLive.profile
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt
    ;;
  *)
    echo "nothing to build"
    ;;
esac
done
