#!/bin/sh

case $TARGET in
  pandoc)
    cabal update
    cabal install hsb2hs
    ;;
  r-devel)
    wget http://cran.rstudio.com/src/base-prerelease/R-latest.tar.gz
    sudo apt-get -qq build-dep r-base
    ;;
  texlive)
    sed -i 's@\$HOME@'"$HOME"'@' TexLive.profile
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt
    # `tlmgr install bibtex` does not install apalike.sty, hence the hack
    wget http://ftp.cs.stanford.edu/tex/bibtex/apalike.sty
    ;;
  *)
    echo "nothing to build"
    ;;
esac
