#!/bin/sh

case $TARGET in
  pandoc)
    git clone https://github.com/jgm/pandoc
    cd pandoc
    git submodule update --init
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    ;;
  r-devel)
    wget http://cran.rstudio.com/src/base-prerelease/R-latest.tar.gz
    sudo apt-get -qq build-dep r-base
    ;;
  texlive)
    sed -i 's@\$HOME@'"$HOME"'@' TexLive.profile
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt
    # `tlmgr install bibtex` does not install apalike.sty, hence the hack
    wget http://ftp.cs.stanford.edu/tex/bibtex/apalike.sty
    ;;
  *)
    echo "nothing to build"
    ;;
esac
